import React from 'react';

interface StoryModalProps {
  title: string;
  storyText: string;
  onClose: () => void;
  lang: 'en' | 'vi';
}

// Simple parser to convert Markdown bold/italic to HTML strings for PDF
const parseMarkdownToHTML = (text: string): string => {
  if (!text) return "";
  let html = text
    .replace(/\*\*(.*?)\*\*/g, '<b>$1</b>') // Bold
    .replace(/\*(.*?)\*/g, '<i>$1</i>');    // Italic
  return html;
};

// Simple parser to convert Markdown to React Nodes
const renderFormattedText = (text: string) => {
  // Split by bold (**...**)
  const parts = text.split(/(\*\*.*?\*\*)/g);
  return parts.map((part, i) => {
    if (part.startsWith('**') && part.endsWith('**')) {
      return <strong key={i} className="text-white font-bold">{part.slice(2, -2)}</strong>;
    }
    // Split by italic (*...*) within non-bold parts
    const subParts = part.split(/(\*.*?\*)/g);
    return subParts.map((subPart, j) => {
       if (subPart.startsWith('*') && subPart.endsWith('*')) {
         return <em key={`${i}-${j}`} className="text-yellow-100 italic">{subPart.slice(1, -1)}</em>;
       }
       return subPart;
    });
  });
};

const StoryModal: React.FC<StoryModalProps> = ({ title, storyText, onClose, lang }) => {
  
  const handleDownloadPDF = () => {
    // Create a new window for printing/saving as PDF
    const printWindow = window.open('', '', 'height=800,width=800');
    
    if (printWindow) {
      const paragraphs = storyText ? storyText.split('\n') : [];
      
      printWindow.document.write('<html><head><title>' + title + '</title>');
      printWindow.document.write(`
        <style>
          @import url('https://fonts.googleapis.com/css2?family=Merriweather:ital,wght@0,300;0,400;0,700;1,400&display=swap');
          body { 
            font-family: 'Merriweather', serif; 
            padding: 40px 60px; 
            line-height: 1.8; 
            color: #1a1a1a; 
            max-width: 800px;
            margin: 0 auto;
          }
          h1 { 
            text-align: center; 
            font-size: 28px; 
            margin-bottom: 40px; 
            text-transform: uppercase; 
            letter-spacing: 1px;
            border-bottom: 2px solid #eee;
            padding-bottom: 20px;
          }
          p { 
            margin-bottom: 20px; 
            font-size: 14px; 
            text-align: justify; 
          }
          p.dialogue {
             margin-left: 20px;
             font-style: italic;
             color: #333;
          }
          .footer {
            margin-top: 50px;
            text-align: center;
            font-size: 12px;
            color: #888;
            border-top: 1px solid #eee;
            padding-top: 20px;
          }
          @media print {
            @page { margin: 2cm; }
            body { -webkit-print-color-adjust: exact; }
          }
        </style>
      `);
      printWindow.document.write('</head><body>');
      
      // Content
      printWindow.document.write(`<h1>${title}</h1>`);
      paragraphs.forEach(p => {
        const trimmed = p.trim();
        if (trimmed) {
          // Detect dialogue logic for PDF styling
          const isDialogue = trimmed.startsWith('"') || trimmed.startsWith('“') || trimmed.startsWith('-');
          const className = isDialogue ? 'class="dialogue"' : '';
          const content = parseMarkdownToHTML(trimmed);
          printWindow.document.write(`<p ${className}>${content}</p>`);
        }
      });
      printWindow.document.write(`<div class="footer">Generated by BananaComics AI</div>`);
      
      printWindow.document.write('</body></html>');
      
      printWindow.document.close();
      printWindow.focus();
      
      // Allow styles to load then print
      setTimeout(() => {
        printWindow.print();
        printWindow.close();
      }, 500);
    }
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/90 backdrop-blur-sm p-4 animate-in fade-in duration-200">
      {/* Changed max-w-2xl to max-w-5xl for wider reading area */}
      <div className="bg-slate-800 w-full max-w-5xl max-h-[90vh] rounded-2xl border border-slate-700 shadow-2xl flex flex-col animate-in zoom-in-95 duration-200">
        
        {/* Header */}
        <div className="p-6 border-b border-slate-700 flex justify-between items-center bg-slate-800/50 rounded-t-2xl shrink-0">
          <div className="flex flex-col">
            <h3 className="text-sm font-bold text-yellow-400 uppercase tracking-widest mb-1">
              {lang === 'vi' ? 'Toàn bộ cốt truyện' : 'Full Story Arc'}
            </h3>
            <h2 className="text-2xl md:text-3xl font-comic text-white tracking-wide line-clamp-1 mr-4">{title}</h2>
          </div>
          <button onClick={onClose} className="text-slate-400 hover:text-white hover:bg-slate-700 p-2 rounded-full transition-all shrink-0">
            <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>
        
        {/* Content - Scrollable Text */}
        <div className="p-8 md:p-12 overflow-y-auto bg-slate-800/80 custom-scrollbar">
          <div className="prose prose-invert prose-lg md:prose-xl max-w-none">
             {storyText ? (
                storyText.split('\n').map((paragraph, index) => {
                  const trimmed = paragraph.trim();
                  if (!trimmed) return null;

                  // Simple heuristic: If starts with quotation mark or dash, treats as dialogue
                  const isDialogue = trimmed.startsWith('"') || trimmed.startsWith('“') || trimmed.startsWith('-');
                  
                  return (
                    <p 
                      key={index} 
                      className={`font-story leading-loose mb-6 last:mb-0 text-lg md:text-xl ${isDialogue ? 'text-slate-100 pl-4 border-l-4 border-slate-600 italic bg-slate-700/30 p-2 rounded-r-lg' : 'text-slate-300'}`}
                    >
                      {renderFormattedText(trimmed)}
                    </p>
                  );
                })
             ) : (
                <p className="text-slate-500 italic text-center font-story">
                  {lang === 'vi' ? 'Đang tạo cốt truyện...' : 'Generating story...'}
                </p>
             )}
          </div>
        </div>

        {/* Footer */}
        <div className="p-4 border-t border-slate-700 bg-slate-800/50 rounded-b-2xl flex justify-between items-center shrink-0">
           <button 
             onClick={handleDownloadPDF}
             className="flex items-center gap-2 px-4 py-2 bg-slate-700 hover:bg-slate-600 text-white rounded-lg font-bold transition-colors border border-slate-600"
             title={lang === 'vi' ? 'Lưu dưới dạng PDF' : 'Save as PDF'}
           >
             <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
               <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
             </svg>
             {lang === 'vi' ? 'Tải PDF' : 'Download PDF'}
           </button>

           <button 
             onClick={onClose}
             className="px-6 py-2 bg-yellow-400 hover:bg-yellow-300 text-slate-900 rounded-lg font-bold transition-colors shadow-lg shadow-yellow-400/20"
           >
             {lang === 'vi' ? 'Đóng' : 'Close'}
           </button>
        </div>
      </div>
    </div>
  );
};

export default StoryModal;